### ISSUE TITLE
IOS 16.4 Support Approach(Solved)

### ISSUE THREAD

**Issue by fabianbrn** [safwanrahman/django-webpush#123] opened 2023-07-25 22:01 UTC
Hey, can you integrate this?
https://taoshu.in/web/push-on-ios.html

**Comment by azmeuk** [comment] 2023-08-02 10:18
Duplicate of #121

**Comment by fabianbrn** [comment] 2023-08-02 11:17
Thats not the same, the Link is the Solution, it works with APNS. It would be great, if implemented in this module

**Comment by fabianbrn** [comment] 2023-08-09 17:09
It works now:)

**Comment by azmeuk** [comment] 2023-08-10 09:42
What do you mean?

**Closed** 2023-08-10 12:08 UTC
